name = "noir-libs"
compatibility_date = "2023-11-03"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

#[env.production.vars]
[vars]
NEXT_PUBLIC_API_URL = "https://api.noir-libs.org"